const e = React.createElement;
function div(config, children) { return e('div', config, children); }
function h1(config, children) { return e('h1', config, children); }
function h2(config, children) { return e('h2', config, children); }
function h3(config, children) { return e('h3', config, children); }
function h4(config, children) { return e('h4', config, children); }
function h5(config, children) { return e('h5', config, children); }
function h6(config, children) { return e('h6', config, children); }
function p(config, children) { return e('p', config, children); }
function a(config, children) { return e('a', config, children); }
function i(config, children) { return e('i', config, children); }
function img(config, children) { return e('img', config, children); }
function span(config, children) { return e('span', config, children); }
function table(config, children) { return e('table', config, children); }
function thead(config, children) { return e('thead', config, children); }
function tbody(config, children) { return e('tbody', config, children); }
function tr(config, children) { return e('tr', config, children); }
function th(config, children) { return e('th', config, children); }
function td(config, children) { return e('td', config, children); }
function form(config, children) { return e('form', config, children); }
function label(config, children) { return e('label', config, children); }
function input(config, children) { return e('input', config, children); }
function select(config, children) { return e('select', config, children); }
function button(config, children) { return e('button', config, children); }